version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cw2
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
  web:
    build:
      context:
        ./
    container_name: php_web
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html/
    ports:
      - "8100:80"
    links:
      - mysql:db
